kind: pipeline
name: release
steps:
    - name: build
      image: alpine
      commands:
          - apk add openjdk8-jre curl
          - ./mpt buildtwitch
          - ./mpt createmodlist HTML build/modlist.html
          - mv build/testcraft-*-twitch.zip build/testcraft-twitch.zip

    - name: publish
      image: plugins/gitea-release
      settings:
          base_url: https://data.tilera.xyz/git
          api_key:
              from_secret: gitea_token
          note: CHANGELOG.md
          title: tag-${DRONE_TAG}
          files:
              - build/testcraft-twitch.zip
              - build/modlist.html
      when:
          event: tag
      depends_on:
          - build

